In [1]:
import tensorflow as tf
from tensorflow import keras

# Define the directory paths
train_dir = 'c:\\Users\\ahmed\\Documents\\Downloads\\Teeth_Dataset\\Training'
test_dir = 'C:\\Users\\ahmed\\Documents\\Downloads\\Teeth_Dataset\\Testing'
val_dir = 'C:\\Users\\ahmed\\Documents\\Downloads\\Teeth_Dataset\\Validation'

# Set some parameters
batch_size = 32
img_height = 255  
img_width = 255   

# Load datasets
train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    train_dir,
    image_size=(img_height, img_width),
)

val_ds = tf.keras.preprocessing.image_dataset_from_directory(
    val_dir,
    image_size=(img_height, img_width),
)

test_ds = tf.keras.preprocessing.image_dataset_from_directory(
    test_dir,
    image_size=(img_height, img_width),
)

# Print dataset information  
class_names = train_ds.class_names  
print("Classes:", class_names)  



Found 3088 files belonging to 7 classes.
Found 1028 files belonging to 7 classes.
Found 1508 files belonging to 10 classes.
Classes: ['CaS', 'CoS', 'Gum', 'MC', 'OC', 'OLP', 'OT']


In [2]:
train_ds

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 255, 255, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>

In [3]:
def preprocess(image, label):
    norm_image = tf.cast(image, tf.float32) / 255.0
    return norm_image, label


In [4]:
#check before
for images, labels in train_ds.take(1):  
    
    print("Image batch shape:", images.shape)  
    print("Label batch shape:", labels.shape)   
    sample_image = images[0]  
    print("Sample image pixel values :", sample_image)

Image batch shape: (32, 255, 255, 3)
Label batch shape: (32,)
Sample image pixel values : tf.Tensor(
[[[ 57.015675  59.015675  46.015675]
  [ 63.1568    65.1568    52.168564]
  [ 90.47642   92.47642   81.47642 ]
  ...
  [176.       112.        84.      ]
  [176.00195  112.001945  84.001945]
  [176.00197  112.00196   84.00196 ]]

 [[ 59.029354  61.029354  48.029354]
  [ 62.117405  64.11741   51.12917 ]
  [ 83.41332   85.41332   74.41332 ]
  ...
  [176.00589  112.00588   84.00588 ]
  [176.99416  112.99416   84.99416 ]
  [177.       113.        85.      ]]

 [[ 63.005844  65.005844  52.005844]
  [ 61.07226   63.07226   50.084026]
  [ 75.332855  77.332855  66.332855]
  ...
  [177.0097   113.009705  85.009705]
  [177.00981  113.0098    85.0098  ]
  [177.00981  113.0098    85.0098  ]]

 ...

 [[225.9902   239.9902   226.9902  ]
  [225.99603  239.99603  226.99603 ]
  [226.9805   240.9805   227.9805  ]
  ...
  [117.02929   77.02929   51.029293]
  [114.00789   74.00789   48.007885]
  [110.99606

In [5]:
def train_data_prep(data,shuffle_size,batch_size):
    data= data.map(preprocess)
    data= data.cache()
    data= data.shuffle(shuffle_size)
    data= data.batch(batch_size)
    data= data.prefetch(1)
    return data

In [6]:
def test_data_prep(data,batch_size):
    data= data.map(preprocess)
    data= data.cache()
    data= data.batch(batch_size)
    data= data.prefetch(1)
    return data

In [7]:
train_ds=train_data_prep(train_ds,1000,32)

In [8]:
test_ds=test_data_prep(test_ds,32)

In [9]:
val_ds=test_data_prep(val_ds,32)

In [10]:
#check after
for images, labels in train_ds.take(1):  
    
    print("Image batch shape:", images.shape)  
    print("Label batch shape:", labels.shape)   
    sample_image = images[0]  
    print("Sample image pixel values :", sample_image)

Image batch shape: (32, 32, 255, 255, 3)
Label batch shape: (32, 32)
Sample image pixel values : tf.Tensor(
[[[[0.40792772 0.31381008 0.21184924]
   [0.41185695 0.3177393  0.21571708]
   [0.4157093  0.32162994 0.21171074]
   ...
   [0.16868144 0.16475987 0.08632089]
   [0.18439074 0.18046917 0.10203776]
   [0.20013085 0.19620928 0.11777025]]

  [[0.44719723 0.3530796  0.2510574 ]
   [0.44719723 0.35307932 0.24327552]
   [0.44712013 0.35291836 0.24306037]
   ...
   [0.25547126 0.25157255 0.16918927]
   [0.27109614 0.2671747  0.18869697]
   [0.2829067  0.27900818 0.19659378]]

  [[0.47051135 0.37639377 0.2665896 ]
   [0.47051156 0.37638626 0.26649   ]
   [0.4704352  0.36855096 0.26243865]
   ...
   [0.36539832 0.36536032 0.27128062]
   [0.3731952  0.3693349  0.28679773]
   [0.3810305  0.38102293 0.2868513 ]]

  ...

  [[0.14898886 0.12545943 0.07055748]
   [0.13333356 0.10978108 0.05483298]
   [0.13348709 0.1060361  0.04321412]
   ...
   [0.56078434 0.6        0.46666667]
   [0.5567708  

In [11]:


input_shape1 = (255, 255, 3)  

teeth_model = tf.keras.models.Sequential([  
    tf.keras.layers.Conv2D(filters=64, kernel_size=(3, 3), activation="relu", input_shape=input_shape1),  
    tf.keras.layers.MaxPooling2D(pool_size=2),  

    tf.keras.layers.Conv2D(filters=128, kernel_size=(3, 3), activation="relu"),  
    tf.keras.layers.MaxPooling2D(pool_size=2),  

    tf.keras.layers.Conv2D(filters=256, kernel_size=(3, 3), activation="relu"),  
    tf.keras.layers.MaxPooling2D(pool_size=2),  

    tf.keras.layers.Flatten(),  

    tf.keras.layers.Dense(units=128, activation='relu'),  
    tf.keras.layers.Dense(units=256, activation="relu"),  
    tf.keras.layers.Dense(units=7, activation="softmax")  
])  



In [12]:
teeth_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 253, 253, 64)      1792      
                                                                 
 max_pooling2d (MaxPooling2  (None, 126, 126, 64)      0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 124, 124, 128)     73856     
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 62, 62, 128)       0         
 g2D)                                                            
                                                                 
 conv2d_2 (Conv2D)           (None, 60, 60, 256)       295168    
                                                                 
 max_pooling2d_2 (MaxPoolin  (None, 30, 30, 256)       0

In [13]:
teeth_model.compile(
    optimizer="adam",
    loss="sparse_categorical_croosentropy",
    metrics=["accuracy"]

)

In [14]:
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)  

  
history = teeth_model.fit(train_ds,  
                    validation_data=(val_ds),  
                    epochs=510,  
                    batch_size=32,  
                    callbacks=[early_stopping])

Epoch 1/510


ValueError: in user code:

    File "c:\Users\ahmed\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\engine\training.py", line 1377, in train_function  *
        return step_function(self, iterator)
    File "c:\Users\ahmed\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\engine\training.py", line 1360, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\ahmed\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\engine\training.py", line 1349, in run_step  **
        outputs = model.train_step(data)
    File "c:\Users\ahmed\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\engine\training.py", line 1126, in train_step
        y_pred = self(x, training=True)
    File "c:\Users\ahmed\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "c:\Users\ahmed\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\engine\input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 255, 255, 3), found shape=(None, None, 255, 255, 3)
